packages:
  - "."
  - "examples/*"

allowBuilds:
  core-js: true
  esbuild: true

minimumReleaseAgeExclude:
  - esbuild@0.28.1
  - vite@8.0.16
  - '@babel/core@7.29.1'

onlyBuiltDependencies:
  - core-js
  - esbuild

overrides:
  esbuild: ^0.28.1
  vite@<=6.4.1: '>=6.4.2'
  "@babel/core": ">=7.29.6"
  vite: ">=8.0.16"
