/**
 * Community metadata returned by Hivemind bridge calls.
 *
 * @remarks
 * This shape contains presentation metadata, moderation/admin team fields, and
 * aggregate pending-post counters that Hive front ends use for community pages.
 *
 * @example
 * ```ts
 * const [community] = await client.hivemind.getCommunity({
 *   name: 'hive-139531',
 *   observer: 'srbde'
 * })
 *
 * console.log(community.title, community.subscribers)
 * ```
 */
export interface CommunityDetail {
    id: number
    name: string
    title: string
    about: string
    lang: string
    type_id: number
    is_nsfw: false
    subscribers: number
    sum_pending: number
    num_pending: number
    num_authors: number
    created_at: string
    avatar_url: string
    context: object
    description: string
    flag_text: string
    settings: {}
    team?: string[]
    admins?: string[]
}

/**
 * Hivemind notification record for an account feed.
 *
 * @remarks
 * Notifications are social/application events generated by Hivemind, not raw
 * block operations. Use account history when exact protocol operations are
 * required.
 *
 * @example
 * ```ts
 * const notifications = await client.hivemind.getAccountNotifications({
 *   account: 'srbde',
 *   limit: 10
 * })
 *
 * console.log(notifications[0]?.msg)
 * ```
 */
export interface Notifications {
    id: number
    type: string
    score: number
    date: string
    msg: string
    url: string
}
